---
- name: Configure balancer role
  hosts: balancers
  remote_user: curtis
  become: yes
  roles:
    - balancer

- name: Configure webservers
  hosts: webservers
  remote_user: curtis
  become: yes
  roles:
    - phphello
...