---
- hosts: node1
  tasks:
          - name: Update machine with custom repos
            blockinfile:
                    dest: /etc/yum.repos.d/customAnsi.repo
                    create: yes
                    block: |
                            [{{ item.name }}]
                            name = {{ item.name }}
                            baseurl = {{ item.url }}
                            gpgcheck = 0
                            enabled = 1
                    marker: "{mark} CUSTOM ANSIBLE BLOCK {{ item.name }}"
                    marker_begin: "\n# BEGIN"
                    marker_end: "# END"
            loop:
              - { name: customBaseOS, url: "http://repo/BaseOS" }
              - { name: customApps, url: "http://repo/Apps" }
...
